/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ashish.hopscotchproject.model.movielist;

public class Abridged_cast
{
	private String id;

	private String name;

	private String[] characters;

	public String getId ()
	{
		return id;
	}

	public void setId (String id)
	{
		this.id = id;
	}

	public String getName ()
	{
		return name;
	}

	public void setName (String name)
	{
		this.name = name;
	}

	public String[] getCharacters ()
	{
		return characters;
	}

	public void setCharacters (String[] characters)
	{
		this.characters = characters;
	}

	@Override
	public String toString()
	{
		return "ClassPojo [id = "+id+", name = "+name+", characters = "+characters+"]";
	}
}