/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ashish.hopscotchproject.model.movielist;

public class Links {
    private String alternate;

    private String reviews;

    private String cast;

    private String self;

    private String similar;

    public String getAlternate() {
        return alternate;
    }

    public void setAlternate(String alternate) {
        this.alternate = alternate;
    }

    public String getReviews() {
        return reviews;
    }

    public void setReviews(String reviews) {
        this.reviews = reviews;
    }

    public String getCast() {
        return cast;
    }

    public void setCast(String cast) {
        this.cast = cast;
    }

    public String getSelf() {
        return self;
    }

    public void setSelf(String self) {
        this.self = self;
    }

    public String getSimilar() {
        return similar;
    }

    public void setSimilar(String similar) {
        this.similar = similar;
    }

    @Override
    public String toString() {
        return "ClassPojo [alternate = " + alternate + ", reviews = " + reviews + ", cast = " + cast + ", self = " + self + ", similar = " + similar + "]";
    }
}