/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ashish.hopscotchproject.model.movielist;

public class Posters {
    private String thumbnail;

    private String detailed;

    private String original;

    private String profile;

    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    public String getDetailed() {
        return detailed;
    }

    public void setDetailed(String detailed) {
        this.detailed = detailed;
    }

    public String getOriginal() {
        return original;
    }

    public void setOriginal(String original) {
        this.original = original;
    }

    public String getProfile() {
        return profile;
    }

    public void setProfile(String profile) {
        this.profile = profile;
    }

    @Override
    public String toString() {
        return "ClassPojo [thumbnail = " + thumbnail + ", detailed = " + detailed + ", original = " + original + ", profile = " + profile + "]";
    }
}