/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ashish.hopscotchproject.model.movielist;

public class Release_dates {
    private String theater;

    public String getTheater() {
        return theater;
    }

    public void setTheater(String theater) {
        this.theater = theater;
    }

    @Override
    public String toString() {
        return "ClassPojo [theater = " + theater + "]";
    }
}